import { 
  Achievement, 
  Goal, 
  JobOpportunity, 
  PlayerProfile, 
  Property, 
  StockItem,
  EducationCourse
} from '../types/game';

export const INITIAL_PLAYER: PlayerProfile = {
  name: 'Alex Vance',
  level: 1,
  xp: 0,
  xpToNext: 100,
  cash: 100,
  energy: 80,
  maxEnergy: 100,
  creditScore: 550,
  reputation: 20,
  housingTier: 1,
  transportationTier: 1,
  foodTier: 1,
  daysPlayed: 1,
  currentHour: 8,
  currentMinute: 0,
  dayOfWeek: 1, // Monday
  skills: {
    handyman: { level: 1, xp: 0, xpToNext: 50 },
    sales: { level: 1, xp: 0, xpToNext: 50 },
    negotiation: { level: 1, xp: 0, xpToNext: 50 },
    finance: { level: 1, xp: 0, xpToNext: 50 },
    business: { level: 1, xp: 0, xpToNext: 50 },
    marketing: { level: 1, xp: 0, xpToNext: 50 },
    management: { level: 1, xp: 0, xpToNext: 50 },
    realEstate: { level: 1, xp: 0, xpToNext: 50 },
    technology: { level: 1, xp: 0, xpToNext: 50 },
  },
  selectedGoalId: 'goal_first_500',
  unlockedFeatures: ['hustle', 'self', 'finance'],
  gems: 10, // Starting bonus gems for store testing
  consecutiveOnTimePayments: 0,
  totalOnTimePayments: 0,
  missedPaymentsCount: 0,
  education: ['high_school_diploma'],
};

export const HOUSING_TIERS = [
  {
    tier: 1,
    name: "Mom's Couch",
    costMonthly: 0,
    purchasePrice: 0,
    energyRestBonus: 60,
    comfort: 15,
    storage: 'None',
    description: 'Free sleeping spot. Poor privacy and sore back in the morning, but zero rent.',
  },
  {
    tier: 2,
    name: 'Shared Room',
    costMonthly: 200,
    purchasePrice: 0,
    energyRestBonus: 75,
    comfort: 35,
    storage: 'Small locker',
    description: 'A modest bunk in an urban flat. Better sleep and a locked drawer for your belongings.',
  },
  {
    tier: 3,
    name: 'Studio Apartment',
    costMonthly: 700,
    purchasePrice: 0,
    energyRestBonus: 85,
    comfort: 55,
    storage: 'Closet & desk',
    description: 'Your own private sanctuary. Includes high-speed internet and quiet work space.',
  },
  {
    tier: 4,
    name: '1-Bedroom Apartment',
    costMonthly: 1200,
    purchasePrice: 0,
    energyRestBonus: 92,
    comfort: 70,
    storage: 'Full apartment',
    description: 'Modern downtown living with a dedicated home office. Unlocks business productivity boosts.',
  },
  {
    tier: 5,
    name: 'Luxury High-Rise Penthouse',
    costMonthly: 3000,
    purchasePrice: 0,
    energyRestBonus: 100,
    comfort: 90,
    storage: 'Walk-in & concierge',
    description: 'Skyline views, private gym, and valet. Massive +15 reputation bonus.',
  },
  {
    tier: 6,
    name: 'Suburban Starter House',
    costMonthly: 400, // Maintenance & taxes
    purchasePrice: 150000,
    energyRestBonus: 100,
    comfort: 80,
    storage: '2-Car Garage & Yard',
    description: 'Real homeownership. Build equity, store tools, and host clients.',
  },
  {
    tier: 7,
    name: 'Executive Hillside Home',
    costMonthly: 900,
    purchasePrice: 420000,
    energyRestBonus: 100,
    comfort: 92,
    storage: 'Expansive Estate',
    description: 'Scenic hilltop sanctuary with pool, executive library, and high security.',
  },
  {
    tier: 8,
    name: 'Private Waterfront Mansion',
    costMonthly: 2200,
    purchasePrice: 1250000,
    energyRestBonus: 100,
    comfort: 98,
    storage: 'Private Compound',
    description: 'Direct dock access, guest wing, and prestige recognized across the city.',
  },
  {
    tier: 9,
    name: 'Billionaire Country Estate',
    costMonthly: 5000,
    purchasePrice: 5000000,
    energyRestBonus: 100,
    comfort: 100,
    storage: 'Hangar & Private Grounds',
    description: 'The pinnacle of architectural supremacy. Complete financial freedom.',
  },
];

export const TRANSPORTATION_TIERS = [
  {
    tier: 1,
    name: 'Walking / Running Shoes',
    cost: 0,
    dailyCost: 0,
    speedMultiplier: 1.0,
    travelEnergyCost: 15,
    description: 'Free, but slow and tires you out quickly. Restricts available job radius.',
  },
  {
    tier: 2,
    name: 'Metro City Bus Pass',
    cost: 45,
    dailyCost: 2,
    speedMultiplier: 1.25,
    travelEnergyCost: 8,
    description: 'Covers major urban transit lines. Unlocks cross-district jobs.',
  },
  {
    tier: 3,
    name: 'Commuter Bicycle',
    cost: 180,
    dailyCost: 1,
    speedMultiplier: 1.5,
    travelEnergyCost: 10,
    description: 'Fast for city traffic. Perfect for low-cost food delivery and micro errands.',
  },
  {
    tier: 4,
    name: 'Used 50cc Scooter',
    cost: 850,
    dailyCost: 4,
    speedMultiplier: 1.8,
    travelEnergyCost: 5,
    canFinance: true,
    downPaymentPercent: 0.20, // $170 down
    financeTermMonths: 12,
    minCreditScore: 540,
    description: 'Zips past traffic jams. Greatly accelerates delivery earnings and gig times.',
  },
  {
    tier: 5,
    name: 'Reliable Used Sedan',
    cost: 3200,
    dailyCost: 12,
    speedMultiplier: 2.2,
    travelEnergyCost: 4,
    canFinance: true,
    downPaymentPercent: 0.20, // $640 down
    financeTermMonths: 24,
    minCreditScore: 580,
    description: 'Weatherproof commuting with cargo trunk. Unlocks regional errands and sales trips. Builds credit on monthly payments!',
  },
  {
    tier: 6,
    name: 'Heavy-Duty Work Truck',
    cost: 8500,
    dailyCost: 22,
    speedMultiplier: 2.1,
    travelEnergyCost: 4,
    canFinance: true,
    downPaymentPercent: 0.20, // $1,700 down
    financeTermMonths: 36,
    minCreditScore: 620,
    description: 'Hauls heavy tools and construction materials. Unlocks high-paying renovation contracts. Solid credit builder!',
  },
  {
    tier: 7,
    name: 'Executive Luxury SUV',
    cost: 38000,
    dailyCost: 35,
    speedMultiplier: 2.6,
    travelEnergyCost: 2,
    canFinance: true,
    downPaymentPercent: 0.15, // $5,700 down
    financeTermMonths: 48,
    minCreditScore: 670,
    description: 'Comfortable client transport. Boosts negotiation power and reputation.',
  },
  {
    tier: 8,
    name: 'Commercial Sprinter Van',
    cost: 54000,
    dailyCost: 45,
    speedMultiplier: 2.3,
    travelEnergyCost: 2,
    canFinance: true,
    downPaymentPercent: 0.15, // $8,100 down
    financeTermMonths: 48,
    minCreditScore: 710,
    description: 'Mobile workshop that equips multiple team members for commercial gigs.',
  },
  {
    tier: 9,
    name: 'Commercial Vehicle Fleet',
    cost: 180000,
    dailyCost: 150,
    speedMultiplier: 3.0,
    travelEnergyCost: 0,
    canFinance: true,
    downPaymentPercent: 0.15, // $27,000 down
    financeTermMonths: 60,
    minCreditScore: 750,
    description: 'Full corporate fleet with dispatch logistics. Multiplies business revenues.',
  },
];

export const MEAL_TIERS = [
  {
    tier: 1,
    name: 'Instant Noodles & Tap Water',
    cost: 5,
    energyRestored: 12,
    description: 'Salty and cheap. Keeps you standing when your bank account is almost zero.',
  },
  {
    tier: 2,
    name: 'Diner Special & Coffee',
    cost: 16,
    energyRestored: 24,
    description: 'Hot eggs, potatoes, and strong roast. Dependable working fuel.',
  },
  {
    tier: 3,
    name: 'Fresh Salad & Salmon Plate',
    cost: 38,
    energyRestored: 38,
    description: 'Balanced organic meal. Sharpens mental focus and boosts energy retention.',
  },
  {
    tier: 4,
    name: 'Private Gourmet Dining',
    cost: 85,
    energyRestored: 55,
    description: 'Prime steak, fresh sides, and artisan espresso. Restores energy and morale.',
  },
];

export const NEIGHBORHOODS = [
  {
    name: 'Southside',
    avgPrice: 85000,
    avgRent: 950,
    demand: 'High',
    crime: 'Moderate',
    growthTrend: '+4.2%',
    description: 'Working-class neighborhood with high rental yields and rising renovator activity.',
  },
  {
    name: 'East District',
    avgPrice: 160000,
    avgRent: 1550,
    demand: 'Very High',
    crime: 'Low',
    growthTrend: '+7.8%',
    description: 'Rapidly gentrifying tech corridor with young professional tenants.',
  },
  {
    name: 'Downtown',
    avgPrice: 340000,
    avgRent: 2800,
    demand: 'High',
    crime: 'Low',
    growthTrend: '+3.5%',
    description: 'High-density commercial and residential core. Premium rents and prestige.',
  },
  {
    name: 'Riverside',
    avgPrice: 220000,
    avgRent: 1950,
    demand: 'High',
    crime: 'Very Low',
    growthTrend: '+6.1%',
    description: 'Scenic waterfront district with new public greenways and family appeal.',
  },
  {
    name: 'North Hills',
    avgPrice: 490000,
    avgRent: 3600,
    demand: 'Moderate',
    crime: 'Minimal',
    growthTrend: '+2.8%',
    description: 'Affluent hilly suburbs with large lots and long-term capital preservation.',
  },
  {
    name: 'Old Town',
    avgPrice: 130000,
    avgRent: 1250,
    demand: 'Moderate',
    crime: 'Moderate',
    growthTrend: '+5.0%',
    description: 'Historic red-brick quarter prime for heritage restorations and creative boutiques.',
  },
  {
    name: 'Industrial Zone',
    avgPrice: 110000,
    avgRent: 1100,
    demand: 'Moderate',
    crime: 'Moderate',
    growthTrend: '+3.0%',
    description: 'Warehouses and contractor lofts. Low acquisition cost with commercial upside.',
  },
  {
    name: 'Lakeside',
    avgPrice: 620000,
    avgRent: 4500,
    demand: 'High',
    crime: 'Minimal',
    growthTrend: '+4.5%',
    description: 'Luxury resort-style living with vacation rental potential.',
  },
];

export const INITIAL_JOBS: JobOpportunity[] = [
  {
    id: 'job_pressure_wash',
    title: 'Pressure Wash Driveway',
    category: 'manual',
    description: 'Blast grime off an oil-stained driveway. Fast honest cash.',
    energyCost: 20,
    timeMinutes: 45,
    payoutBase: 60,
    bonusTipMax: 15,
    skillRewards: [{ skill: 'handyman', xp: 8 }],
    xpReward: 12,
    icon: 'Sparkles',
  },
  {
    id: 'job_yard_cleanup',
    title: 'Overgrown Yard Cleanup',
    category: 'manual',
    description: 'Rake leaves, trim thorn bushes, and bag lawn waste.',
    energyCost: 35,
    timeMinutes: 120,
    payoutBase: 110,
    bonusTipMax: 25,
    skillRewards: [
      { skill: 'handyman', xp: 12 },
      { skill: 'negotiation', xp: 4 },
    ],
    xpReward: 20,
    icon: 'Trees',
  },
  {
    id: 'job_food_delivery',
    title: 'Food Delivery Rush',
    category: 'delivery',
    description: 'Rush takeout orders across town during lunch hour.',
    energyCost: 15,
    timeMinutes: 60,
    payoutBase: 50,
    bonusTipMax: 20,
    requiredTransportTier: 2,
    skillRewards: [
      { skill: 'sales', xp: 6 },
      { skill: 'management', xp: 4 },
    ],
    xpReward: 15,
    icon: 'Bike',
  },
  {
    id: 'job_social_media',
    title: 'Local Cafe Social Media Promo',
    category: 'tech',
    description: 'Shoot photos and run targeted posts for a neighborhood bakery.',
    energyCost: 15,
    timeMinutes: 60,
    payoutBase: 80,
    bonusTipMax: 15,
    skillRewards: [
      { skill: 'marketing', xp: 12 },
      { skill: 'technology', xp: 6 },
    ],
    xpReward: 18,
    icon: 'Smartphone',
  },
  {
    id: 'job_furniture_assembly',
    title: 'Flat-Pack Furniture Assembly',
    category: 'manual',
    description: 'Assemble an entire bedroom wardrobe and dining set with hand tools.',
    energyCost: 25,
    timeMinutes: 90,
    payoutBase: 95,
    bonusTipMax: 20,
    requiredSkill: { skill: 'handyman', minLevel: 2 },
    skillRewards: [{ skill: 'handyman', xp: 15 }],
    xpReward: 18,
    icon: 'Wrench',
  },
  {
    id: 'job_door_sales',
    title: 'Solar Panel Door Outreach',
    category: 'sales',
    description: 'Pitch residential clean energy assessments door-to-door.',
    energyCost: 30,
    timeMinutes: 120,
    payoutBase: 140,
    bonusTipMax: 50,
    requiredSkill: { skill: 'sales', minLevel: 2 },
    skillRewards: [
      { skill: 'sales', xp: 16 },
      { skill: 'negotiation', xp: 8 },
    ],
    xpReward: 25,
    icon: 'Megaphone',
  },
  {
    id: 'job_freelance_web',
    title: 'Small Business Website Landing Page',
    category: 'tech',
    description: 'Code a clean responsive portfolio site for a dental clinic.',
    energyCost: 20,
    timeMinutes: 150,
    payoutBase: 240,
    bonusTipMax: 40,
    requiredSkill: { skill: 'technology', minLevel: 3 },
    skillRewards: [
      { skill: 'technology', xp: 20 },
      { skill: 'business', xp: 8 },
    ],
    xpReward: 35,
    icon: 'Laptop',
  },
  {
    id: 'job_subcontractor_plumbing',
    title: 'Commercial Pipe Emergency Assist',
    category: 'manual',
    description: 'Help a master contractor trace and seal a high-pressure line leak.',
    energyCost: 35,
    timeMinutes: 180,
    payoutBase: 360,
    bonusTipMax: 60,
    requiredSkill: { skill: 'handyman', minLevel: 5 },
    skillRewards: [
      { skill: 'handyman', xp: 25 },
      { skill: 'realEstate', xp: 10 },
    ],
    xpReward: 45,
    icon: 'Pipette',
  },
  {
    id: 'job_commercial_audit',
    title: 'Rental Portfolio Bookkeeping Audit',
    category: 'management',
    description: 'Reconcile tax receipts and tenant ledgers for a local landlord.',
    energyCost: 20,
    timeMinutes: 120,
    payoutBase: 310,
    bonusTipMax: 50,
    requiredSkill: { skill: 'finance', minLevel: 4 },
    skillRewards: [
      { skill: 'finance', xp: 24 },
      { skill: 'realEstate', xp: 12 },
    ],
    xpReward: 40,
    icon: 'Briefcase',
  },
  {
    id: 'job_commercial_electrician',
    title: 'Certified Commercial Electrician',
    category: 'manual',
    description: 'Wire 3-phase industrial breaker panels for commercial office parks.',
    energyCost: 35,
    timeMinutes: 180,
    payoutBase: 580,
    bonusTipMax: 90,
    requiredTransportTier: 4, // Scooter/Sedan
    requiredEducation: {
      id: 'edu_trade_cert',
      name: 'Vocational Trade & Electrical Certification',
    },
    skillRewards: [
      { skill: 'handyman', xp: 35 },
      { skill: 'technology', xp: 25 },
    ],
    xpReward: 55,
    icon: 'Wrench',
  },
  {
    id: 'job_b2b_sales_consultant',
    title: 'B2B Enterprise Solutions Consultant',
    category: 'sales',
    description: 'Deliver boardroom sales pitches and close corporate software service deals.',
    energyCost: 25,
    timeMinutes: 150,
    payoutBase: 760,
    bonusTipMax: 180,
    requiredEducation: {
      id: 'edu_marketing_associate',
      name: 'Associate in Digital Marketing & Sales Strategy',
    },
    skillRewards: [
      { skill: 'sales', xp: 40 },
      { skill: 'negotiation', xp: 30 },
      { skill: 'marketing', xp: 20 },
    ],
    xpReward: 65,
    icon: 'Megaphone',
  },
  {
    id: 'job_software_engineer',
    title: 'Full-Stack Cloud Software Engineer',
    category: 'tech',
    description: 'Architect distributed cloud backends, microservices, and high-load APIs.',
    energyCost: 30,
    timeMinutes: 180,
    payoutBase: 980,
    bonusTipMax: 150,
    requiredEducation: {
      id: 'edu_cs_bachelor',
      name: 'B.S. in Computer Science & Cloud Engineering',
    },
    skillRewards: [
      { skill: 'technology', xp: 50 },
      { skill: 'business', xp: 25 },
    ],
    xpReward: 80,
    icon: 'Laptop',
  },
  {
    id: 'job_commercial_broker',
    title: 'Commercial Real Estate Deal Underwriter',
    category: 'management',
    description: 'Structure institutional commercial real estate acquisitions and debt syndicates.',
    energyCost: 30,
    timeMinutes: 210,
    payoutBase: 1450,
    bonusTipMax: 300,
    requiredEducation: {
      id: 'edu_realestate_finance',
      name: 'B.B.A. in Real Estate & Commercial Asset Finance',
    },
    skillRewards: [
      { skill: 'realEstate', xp: 55 },
      { skill: 'finance', xp: 45 },
      { skill: 'negotiation', xp: 35 },
    ],
    xpReward: 100,
    icon: 'Building2',
  },
  {
    id: 'job_hedge_fund_analyst',
    title: 'Quantitative Portfolio Risk Analyst',
    category: 'management',
    description: 'Model systemic risk factors and optimize algorithmic equities arbitrage.',
    energyCost: 35,
    timeMinutes: 240,
    payoutBase: 1850,
    bonusTipMax: 400,
    requiredEducation: {
      id: 'edu_cfa_license',
      name: 'Chartered Financial Analyst (CFA) & Series License',
    },
    skillRewards: [
      { skill: 'finance', xp: 65 },
      { skill: 'business', xp: 40 },
    ],
    xpReward: 125,
    icon: 'TrendingUp',
  },
  {
    id: 'job_corporate_managing_director',
    title: 'Corporate Operations Managing Director',
    category: 'management',
    description: 'Command multi-facility operations, high-stakes enterprise mergers, and board strategy.',
    energyCost: 45,
    timeMinutes: 300,
    payoutBase: 2900,
    bonusTipMax: 650,
    requiredEducation: {
      id: 'edu_executive_mba',
      name: 'Executive MBA & Corporate Leadership',
    },
    skillRewards: [
      { skill: 'management', xp: 70 },
      { skill: 'business', xp: 60 },
      { skill: 'negotiation', xp: 50 },
      { skill: 'finance', xp: 40 },
    ],
    xpReward: 180,
    icon: 'Briefcase',
  },
];

export const EDUCATION_COURSES: EducationCourse[] = [
  {
    id: 'edu_trade_cert',
    name: 'Vocational Trade & Electrical Certification',
    degreeType: 'Certificate',
    institution: 'Metro Technical Institute',
    cost: 850,
    energyCost: 30,
    timeMinutes: 180,
    description: 'Hands-on training in commercial electrical wiring, high-voltage safety, and building codes.',
    skillsBoosted: [
      { skill: 'handyman', xp: 85, label: '+85 Handyman XP' },
      { skill: 'technology', xp: 45, label: '+45 Technology XP' },
    ],
    unlocksJobsSummary: 'Unlocks Certified Commercial Electrician & High-Tier Handyman contracts',
    icon: 'Wrench',
  },
  {
    id: 'edu_marketing_associate',
    name: 'Associate in Digital Marketing & Sales Strategy',
    degreeType: 'Associate',
    institution: 'City Community College',
    cost: 2200,
    energyCost: 35,
    timeMinutes: 240,
    description: 'Master omnichannel customer acquisition funnels, behavioral psychology, and high-ticket B2B closing.',
    skillsBoosted: [
      { skill: 'sales', xp: 120, label: '+120 Sales XP' },
      { skill: 'marketing', xp: 110, label: '+110 Marketing XP' },
      { skill: 'negotiation', xp: 60, label: '+60 Negotiation XP' },
    ],
    unlocksJobsSummary: 'Unlocks B2B Enterprise Solutions Consultant & Marketing Director gigs',
    icon: 'Megaphone',
  },
  {
    id: 'edu_cs_bachelor',
    name: 'B.S. in Computer Science & Cloud Engineering',
    degreeType: 'Bachelor',
    institution: 'State Institute of Technology',
    cost: 7500,
    energyCost: 45,
    timeMinutes: 360,
    description: 'Comprehensive study of distributed systems, cloud infrastructure, algorithm complexity, and software architecture.',
    skillsBoosted: [
      { skill: 'technology', xp: 260, label: '+260 Technology XP' },
      { skill: 'business', xp: 90, label: '+90 Business XP' },
      { skill: 'management', xp: 70, label: '+70 Management XP' },
    ],
    unlocksJobsSummary: 'Unlocks Full-Stack Cloud Software Engineer ($980/shift)',
    icon: 'Laptop',
  },
  {
    id: 'edu_realestate_finance',
    name: 'B.B.A. in Real Estate & Commercial Asset Finance',
    degreeType: 'Bachelor',
    institution: 'Riverside University of Commerce',
    cost: 9200,
    energyCost: 45,
    timeMinutes: 360,
    description: 'Institutional asset valuation, commercial property underwriting, cash flow modeling, and debt structuring.',
    skillsBoosted: [
      { skill: 'realEstate', xp: 240, label: '+240 Real Estate XP' },
      { skill: 'finance', xp: 220, label: '+220 Finance XP' },
      { skill: 'negotiation', xp: 140, label: '+140 Negotiation XP' },
    ],
    unlocksJobsSummary: 'Unlocks Commercial Real Estate Deal Underwriter ($1,450/shift)',
    icon: 'Building2',
  },
  {
    id: 'edu_cfa_license',
    name: 'Chartered Financial Analyst (CFA) & Series License',
    degreeType: 'License',
    institution: 'Global Institute of Financial Markets',
    cost: 5800,
    energyCost: 40,
    timeMinutes: 300,
    description: 'Advanced asset valuation, portfolio management, quantitative risk mathematics, and regulatory compliance.',
    skillsBoosted: [
      { skill: 'finance', xp: 250, label: '+250 Finance XP' },
      { skill: 'business', xp: 130, label: '+130 Business XP' },
      { skill: 'negotiation', xp: 80, label: '+80 Negotiation XP' },
    ],
    unlocksJobsSummary: 'Unlocks Quantitative Portfolio Risk Analyst ($1,850/shift)',
    icon: 'TrendingUp',
  },
  {
    id: 'edu_executive_mba',
    name: 'Executive MBA & Corporate Leadership',
    degreeType: 'Master',
    institution: 'Vanguard Graduate Business School',
    cost: 22000,
    energyCost: 55,
    timeMinutes: 480,
    description: 'Elite corporate governance, corporate restructuring, venture syndication, and executive board management.',
    skillsBoosted: [
      { skill: 'management', xp: 320, label: '+320 Management XP' },
      { skill: 'business', xp: 280, label: '+280 Business XP' },
      { skill: 'negotiation', xp: 220, label: '+220 Negotiation XP' },
      { skill: 'finance', xp: 180, label: '+180 Finance XP' },
    ],
    unlocksJobsSummary: 'Unlocks Corporate Operations Managing Director ($2,900/shift)',
    prerequisiteEduId: 'edu_cs_bachelor',
    prerequisiteEduName: 'Requires Bachelor Degree (B.S. Computer Science or B.B.A. Real Estate)',
    minPlayerLevel: 8,
    icon: 'GraduationCap',
  },
];

export const INITIAL_STOCKS: StockItem[] = [
  {
    id: 'stock_mgc',
    ticker: 'MGC',
    name: 'MegaCore Technologies',
    category: 'bluechip',
    price: 324.5,
    previousClose: 320.0,
    changePercent: 1.41,
    dividendYield: 0.018,
    volatility: 0.035,
    history: [305, 310, 308, 315, 312, 318, 321, 320, 324.5],
    sector: 'Cloud & AI Hardware',
    description: 'Global computing conglomerate powering corporate cloud and quantum chips.',
  },
  {
    id: 'stock_gge',
    ticker: 'GGE',
    name: 'GreenGrid Energy',
    category: 'growth',
    price: 48.2,
    previousClose: 46.5,
    changePercent: 3.65,
    dividendYield: 0.024,
    volatility: 0.065,
    history: [42, 44, 43, 46, 45, 47, 46.5, 48.2],
    sector: 'Clean Infrastructure',
    description: 'Next-gen solar battery arrays and high-voltage metropolitan transmission grids.',
  },
  {
    id: 'stock_ubd',
    ticker: 'UBD',
    name: 'UrbanBuild Construction',
    category: 'bluechip',
    price: 84.1,
    previousClose: 85.0,
    changePercent: -1.06,
    dividendYield: 0.042,
    volatility: 0.04,
    history: [88, 86, 87, 85, 84, 85.5, 85.0, 84.1],
    sector: 'Commercial Real Estate Dev',
    description: 'Civil engineering titan building transit rail, skyscrapers, and civic bridges.',
  },
  {
    id: 'stock_fmt',
    ticker: 'FMT',
    name: 'FreshMart Grocery Corp',
    category: 'bluechip',
    price: 62.4,
    previousClose: 62.1,
    changePercent: 0.48,
    dividendYield: 0.038,
    volatility: 0.02,
    history: [60, 61, 61.5, 62, 61.8, 62.1, 62.4],
    sector: 'Consumer Staples',
    description: 'Recession-resilient nationwide grocery chains with automated fulfillment centers.',
  },
  {
    id: 'stock_cns',
    ticker: 'CNS',
    name: 'CloudNine Cyber Systems',
    category: 'growth',
    price: 112.8,
    previousClose: 108.0,
    changePercent: 4.44,
    dividendYield: 0.005,
    volatility: 0.08,
    history: [95, 99, 104, 102, 105, 108, 112.8],
    sector: 'Enterprise Security',
    description: 'High-growth automated threat detection defending major banking networks.',
  },
  {
    id: 'stock_nvb',
    ticker: 'NVB',
    name: 'NovaBio Therapeutics',
    category: 'penny',
    price: 4.85,
    previousClose: 4.2,
    changePercent: 15.48,
    dividendYield: 0.0,
    volatility: 0.16,
    history: [3.8, 4.1, 3.9, 4.5, 4.0, 4.2, 4.85],
    sector: 'Biotechnology Clinical',
    description: 'Volatile biotech startup undergoing FDA phase III clinical trials for rare enzyme therapies.',
  },
  {
    id: 'stock_ttl',
    ticker: 'TTL',
    name: 'Titan Logistics Freight',
    category: 'bluechip',
    price: 156.0,
    previousClose: 158.2,
    changePercent: -1.39,
    dividendYield: 0.031,
    volatility: 0.03,
    history: [150, 153, 155, 159, 157, 158.2, 156.0],
    sector: 'Global Transport',
    description: 'Intermodal freight trains, container ships, and automated hub terminals.',
  },
  {
    id: 'stock_apx',
    ticker: 'APX',
    name: 'Apex Commercial REIT',
    category: 'reit',
    price: 76.5,
    previousClose: 75.8,
    changePercent: 0.92,
    dividendYield: 0.068,
    volatility: 0.025,
    history: [74, 74.5, 75, 75.2, 75.5, 75.8, 76.5],
    sector: 'Real Estate Investment Trust',
    description: 'Institutional portfolio holding class-A medical offices and distribution logistics.',
  },
  {
    id: 'stock_hzr',
    ticker: 'HZR',
    name: 'Horizon Residential REIT',
    category: 'reit',
    price: 54.2,
    previousClose: 53.9,
    changePercent: 0.56,
    dividendYield: 0.062,
    volatility: 0.03,
    history: [52, 53, 53.5, 53.8, 54, 53.9, 54.2],
    sector: 'Multifamily Housing',
    description: 'Owns 12,000 suburban rental units paying consistent monthly dividends.',
  },
  {
    id: 'stock_mgi',
    ticker: 'MGI',
    name: 'Metro Top 100 Index Fund',
    category: 'index',
    price: 215.0,
    previousClose: 214.2,
    changePercent: 0.37,
    dividendYield: 0.022,
    volatility: 0.015,
    history: [208, 210, 212, 211, 213, 214.2, 215.0],
    sector: 'Broad Market ETF',
    description: 'Diversified basket tracking the top 100 industrial, financial, and tech giants.',
  },
];

export const INITIAL_PROPERTIES_MARKET: Property[] = [
  {
    id: 'prop_404_maple',
    address: '404 Maple Street',
    neighborhood: 'Southside',
    askingPrice: 85000,
    currentValue: 85000,
    estimatedRent: 950,
    overallCondition: 62,
    monthlyExpenses: 220,
    daysOnMarket: 14,
    isOwned: false,
    image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=600&q=80',
    areas: [
      { id: 'roof', name: 'Roof & Gutters', condition: 55, repairCost: 3500, diySkillReq: 3, diyEnergyCost: 40 },
      { id: 'kitchen', name: 'Kitchen Cabinets & Counters', condition: 60, repairCost: 2800, diySkillReq: 2, diyEnergyCost: 30 },
      { id: 'bathroom', name: 'Bathroom & Tiles', condition: 45, repairCost: 2200, diySkillReq: 3, diyEnergyCost: 30 },
      { id: 'electrical', name: 'Electrical Panel & Wiring', condition: 70, repairCost: 1800, diySkillReq: 4, diyEnergyCost: 25 },
      { id: 'plumbing', name: 'Plumbing & Water Heater', condition: 50, repairCost: 2100, diySkillReq: 4, diyEnergyCost: 35 },
      { id: 'flooring', name: 'Hardwood & Vinyl Flooring', condition: 75, repairCost: 1600, diySkillReq: 2, diyEnergyCost: 25 },
      { id: 'exterior', name: 'Exterior Siding & Porch', condition: 80, repairCost: 1000, diySkillReq: 1, diyEnergyCost: 20 },
    ],
    collectedRentUnclaimed: 0,
  },
  {
    id: 'prop_12_elm',
    address: '12 Elm Court',
    neighborhood: 'East District',
    askingPrice: 165000,
    currentValue: 165000,
    estimatedRent: 1600,
    overallCondition: 78,
    monthlyExpenses: 340,
    daysOnMarket: 6,
    isOwned: false,
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=600&q=80',
    areas: [
      { id: 'roof', name: 'Roof & Gutters', condition: 85, repairCost: 1500, diySkillReq: 3, diyEnergyCost: 35 },
      { id: 'kitchen', name: 'Kitchen Cabinets & Counters', condition: 75, repairCost: 2000, diySkillReq: 2, diyEnergyCost: 25 },
      { id: 'bathroom', name: 'Bathroom & Tiles', condition: 80, repairCost: 1500, diySkillReq: 3, diyEnergyCost: 25 },
      { id: 'electrical', name: 'Electrical Panel & Wiring', condition: 90, repairCost: 800, diySkillReq: 4, diyEnergyCost: 20 },
      { id: 'plumbing', name: 'Plumbing & Water Heater', condition: 70, repairCost: 1900, diySkillReq: 4, diyEnergyCost: 30 },
      { id: 'flooring', name: 'Hardwood & Vinyl Flooring', condition: 85, repairCost: 1200, diySkillReq: 2, diyEnergyCost: 20 },
      { id: 'exterior', name: 'Exterior Siding & Porch', condition: 60, repairCost: 2400, diySkillReq: 2, diyEnergyCost: 25 },
    ],
    collectedRentUnclaimed: 0,
  },
  {
    id: 'prop_78_riverside',
    address: '78 Riverside Avenue',
    neighborhood: 'Riverside',
    askingPrice: 210000,
    currentValue: 210000,
    estimatedRent: 2050,
    overallCondition: 50,
    monthlyExpenses: 410,
    daysOnMarket: 28,
    isOwned: false,
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=600&q=80',
    areas: [
      { id: 'roof', name: 'Roof & Gutters', condition: 40, repairCost: 6500, diySkillReq: 4, diyEnergyCost: 45 },
      { id: 'kitchen', name: 'Kitchen Cabinets & Counters', condition: 45, repairCost: 5000, diySkillReq: 3, diyEnergyCost: 35 },
      { id: 'bathroom', name: 'Bathroom & Tiles', condition: 55, repairCost: 3200, diySkillReq: 3, diyEnergyCost: 30 },
      { id: 'electrical', name: 'Electrical Panel & Wiring', condition: 60, repairCost: 2800, diySkillReq: 4, diyEnergyCost: 30 },
      { id: 'plumbing', name: 'Plumbing & Water Heater', condition: 40, repairCost: 3900, diySkillReq: 4, diyEnergyCost: 40 },
      { id: 'flooring', name: 'Hardwood & Vinyl Flooring', condition: 50, repairCost: 3000, diySkillReq: 2, diyEnergyCost: 30 },
      { id: 'exterior', name: 'Exterior Siding & Porch', condition: 60, repairCost: 2800, diySkillReq: 2, diyEnergyCost: 25 },
    ],
    collectedRentUnclaimed: 0,
  },
  {
    id: 'prop_310_concord',
    address: '310 Concord Plaza',
    neighborhood: 'Downtown',
    askingPrice: 320000,
    currentValue: 320000,
    estimatedRent: 2750,
    overallCondition: 88,
    monthlyExpenses: 520,
    daysOnMarket: 4,
    isOwned: false,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
    areas: [
      { id: 'roof', name: 'Roof & Gutters', condition: 95, repairCost: 800, diySkillReq: 3, diyEnergyCost: 25 },
      { id: 'kitchen', name: 'Kitchen Cabinets & Counters', condition: 90, repairCost: 1200, diySkillReq: 2, diyEnergyCost: 20 },
      { id: 'bathroom', name: 'Bathroom & Tiles', condition: 90, repairCost: 1100, diySkillReq: 3, diyEnergyCost: 20 },
      { id: 'electrical', name: 'Electrical Panel & Wiring', condition: 95, repairCost: 600, diySkillReq: 4, diyEnergyCost: 15 },
      { id: 'plumbing', name: 'Plumbing & Water Heater', condition: 85, repairCost: 1400, diySkillReq: 4, diyEnergyCost: 25 },
      { id: 'flooring', name: 'Hardwood & Vinyl Flooring', condition: 90, repairCost: 1000, diySkillReq: 2, diyEnergyCost: 20 },
      { id: 'exterior', name: 'Exterior Siding & Porch', condition: 70, repairCost: 2200, diySkillReq: 2, diyEnergyCost: 25 },
    ],
    collectedRentUnclaimed: 0,
  },
  {
    id: 'prop_55_forge',
    address: '55 Forge Alley',
    neighborhood: 'Industrial Zone',
    askingPrice: 98000,
    currentValue: 98000,
    estimatedRent: 1150,
    overallCondition: 45,
    monthlyExpenses: 210,
    daysOnMarket: 35,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80',
    isOwned: false,
    areas: [
      { id: 'roof', name: 'Roof & Gutters', condition: 35, repairCost: 5200, diySkillReq: 3, diyEnergyCost: 45 },
      { id: 'kitchen', name: 'Kitchen Cabinets & Counters', condition: 40, repairCost: 2500, diySkillReq: 2, diyEnergyCost: 30 },
      { id: 'bathroom', name: 'Bathroom & Tiles', condition: 50, repairCost: 2000, diySkillReq: 3, diyEnergyCost: 30 },
      { id: 'electrical', name: 'Electrical Panel & Wiring', condition: 40, repairCost: 3500, diySkillReq: 4, diyEnergyCost: 35 },
      { id: 'plumbing', name: 'Plumbing & Water Heater', condition: 50, repairCost: 2400, diySkillReq: 4, diyEnergyCost: 35 },
      { id: 'flooring', name: 'Hardwood & Vinyl Flooring', condition: 60, repairCost: 1800, diySkillReq: 2, diyEnergyCost: 25 },
      { id: 'exterior', name: 'Exterior Siding & Porch', condition: 40, repairCost: 3800, diySkillReq: 2, diyEnergyCost: 35 },
    ],
    collectedRentUnclaimed: 0,
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  { id: 'ach_first_dollar', title: 'First Dollar', description: 'Earn your first $100 from gigs or jobs.', icon: 'Banknote', unlocked: false, rewardXp: 50 },
  { id: 'ach_first_paycheck', title: 'First Paycheck', description: 'Complete your first successful job shift.', icon: 'Briefcase', unlocked: false, rewardXp: 40 },
  { id: 'ach_credit_builder', title: 'Credit Climber', description: 'Raise your credit score above 650.', icon: 'Award', unlocked: false, rewardXp: 75 },
  { id: 'ach_first_stock', title: 'Wall Street Rookie', description: 'Purchase your first company stock or REIT share.', icon: 'TrendingUp', unlocked: false, rewardXp: 60 },
  { id: 'ach_first_business', title: 'Founder', description: 'Launch your first commercial micro-business.', icon: 'Store', unlocked: false, rewardXp: 120 },
  { id: 'ach_first_key', title: 'First Key', description: 'Acquire your very first investment property.', icon: 'Key', unlocked: false, rewardXp: 200 },
  { id: 'ach_landlord', title: 'Landlord', description: 'Collect your first monthly tenant rental payment.', icon: 'Home', unlocked: false, rewardXp: 100 },
  { id: 'ach_master_builder', title: 'Master Renovator', description: 'Fully renovate every area of a property to 90% condition.', icon: 'Hammer', unlocked: false, rewardXp: 150 },
  { id: 'ach_diversified', title: 'Asset Master', description: 'Hold assets simultaneously in Stocks, Real Estate, and Business.', icon: 'Layers', unlocked: false, rewardXp: 180 },
  { id: 'ach_millionaire', title: 'Seven-Figure Net Worth', description: 'Surpass $1,000,000 total net worth.', icon: 'Crown', unlocked: false, rewardXp: 500 },
];

export const INITIAL_GOALS: Goal[] = [
  { id: 'goal_first_500', title: 'Emergency Hustle Cushion', targetValue: 500, type: 'cash', rewardTitle: 'Survivor Badge' },
  { id: 'goal_first_business', title: 'Launch a Business', targetValue: 1, type: 'businesses', rewardTitle: 'Entrepreneur Title' },
  { id: 'goal_first_property', title: 'Buy First Rental Property', targetValue: 1, type: 'properties', rewardTitle: 'Property Investor' },
  { id: 'goal_reach_700_credit', title: 'Reach 700+ Credit Score', targetValue: 700, type: 'credit', rewardTitle: 'Prime Borrower' },
  { id: 'goal_networth_100k', title: 'Cross $100,000 Net Worth', targetValue: 100000, type: 'networth', rewardTitle: 'Six-Figure Club' },
  { id: 'goal_networth_1m', title: 'Empire: $1,000,000 Net Worth', targetValue: 1000000, type: 'networth', rewardTitle: 'Empire Tycoon' },
];

export const AI_OPPONENTS = [
  { name: 'Marcus', archetype: 'Aggressive Investor', style: 'Bids boldly on speculative fixer-uppers and high-growth stocks.' },
  { name: 'Sarah', archetype: 'Conservative Landlord', style: 'Focuses strictly on stable cash-flowing rentals with good tenants.' },
  { name: 'David', archetype: 'Business Builder', style: 'Acquires operations and reinvests heavily in corporate contracts.' },
  { name: 'Nina', archetype: 'Property Flipper', style: 'Aggressively buys distressed homes, conducts fast flips, and takes cash.' },
];
